"""CompaSSE core: PE, address libraries, versions, settings, backups."""
from .addresslib import (collect_lib_bins,
    convert_format5_to_format2, extract_version_from_filename,
    find_versionlib_in_dirs,
    load_matching_lib,
    module_supports_fmt5_bytes, parse_format5, parse_library_any)
from .backups import (backup_bytes, backup_path,
    list_backups_all, restore_backups_all, restore_one)
from .pe import (HAS_CAPSTONE, capstone_md, find_export_rva,
    find_pe_sections, get_functions_from_pdata, iat_range, load_exe_sections,
    pe_build_dt, rva_to_offset)
from .settings import (clear_mo2_ini, save_game_exe,
    save_mo2_ini, saved_game_exe, saved_mo2_ini)
from .tools import (TOOLS, ToolContext, ToolSpec, register_tool)
from .config import CONFIG_NAME
from .touched import (TOUCHED_NAME, add_touched, prune_missing,
    read_touched, remove_touched, seed_from_backups, touched_path)
from .skiplist import (add_legacy_skip, is_legacy_skipped,
    is_versionless_plugin, pe_build_year,
    remove_legacy_skip)
from .translations import (build_translations, merge_translation_block,
    mint_missing_translations, read_translation_table, table_build_stamp,
    table_header, table_state, _table_header)
from .versions import (FLAG_STRUCT_OFFSET, KVI_ADDR_LIB_POST_AE, KVI_KNOWN,
    KVI_SIGNATURES, KVI_STRUCTS_POST629, KVI_TARGET, KVIEX_ADDR_LIB_V5,
    STRUCTURAL_CUTOFFS, VERSION, VERSION_INDEP_OFFSET,
    _built_before_1_7_99, _packed_to_ver, _v5_enforced,
    built_before_1_7_99, compat_match, crossed_cutoffs, packed_to_ver,
    runtime_version_from_exe, unpack_version, v5_enforced)

__all__ = [
    "collect_lib_bins",
    "convert_format5_to_format2",
    "extract_version_from_filename",
    "find_versionlib_in_dirs",
    "load_matching_lib",
    "module_supports_fmt5_bytes",
    "parse_format5",
    "parse_library_any",
    "backup_bytes",
    "backup_path",
    "list_backups_all",
    "restore_backups_all",
    "restore_one",
    "HAS_CAPSTONE",
    "capstone_md",
    "find_export_rva",
    "find_pe_sections",
    "get_functions_from_pdata",
    "iat_range",
    "load_exe_sections",
    "pe_build_dt",
    "rva_to_offset",
    "clear_mo2_ini",
    "save_game_exe",
    "save_mo2_ini",
    "saved_game_exe",
    "saved_mo2_ini",
    "TOOLS",
    "ToolContext",
    "ToolSpec",
    "register_tool",
    "TOUCHED_NAME",
    "CONFIG_NAME",
    "add_touched",
    "prune_missing",
    "read_touched",
    "remove_touched",
    "seed_from_backups",
    "touched_path",
    "add_legacy_skip",
    "is_legacy_skipped",
    "is_versionless_plugin",
    "pe_build_year",
    "remove_legacy_skip",
    "build_translations",
    "merge_translation_block",
    "mint_missing_translations",
    "read_translation_table",
    "table_build_stamp",
    "table_header",
    "table_state",
    "_table_header",
    "FLAG_STRUCT_OFFSET",
    "VERSION_INDEP_OFFSET",
    "KVI_ADDR_LIB_POST_AE",
    "KVI_KNOWN",
    "KVI_SIGNATURES",
    "KVI_STRUCTS_POST629",
    "KVI_TARGET",
    "KVIEX_ADDR_LIB_V5",
    "STRUCTURAL_CUTOFFS",
    "VERSION",
    "_built_before_1_7_99",
    "built_before_1_7_99",
    "_packed_to_ver",
    "packed_to_ver",
    "_v5_enforced",
    "v5_enforced",
    "compat_match",
    "crossed_cutoffs",
    "runtime_version_from_exe",
    "unpack_version",
]
